--- # Tableau Server API Info
  tableau-base-url: ""
  tableau-site: ""
  tableau-username: ""
  tableau-password: ""
  # leave blank to gather flows from all projects
  projects-to-refresh-from:
    - "default"